# Site settings

name: Derick Ruiz
email: derick.r.ruiz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Derick Ruiz is a front-end web developer with a focus on responsive
  websites.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://derickruiz.com" # the base hostname & protocol for your site
social_services:
  twitter: drrrruiz
  github: derickruiz
  codepen: derickruiz
  instagram: iamderickruiz

# Build settings
markdown: kramdown

permalink: /:title

collections:
  work:
    output: true
    permalink: /work/:path
  coverletter:
      output: true
      permalink: /:path

navigation:
 - title: About
   url: /about
 - title: Articles
   url: /articles
 - title: Works
   url: /works
 - title: Contact
   url: /contact

gems: ["liquid_reading_time"]

destination: ../derickruiz.github.io/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      parentTitle: "Articles"
      parentUrl: "/articles"
  -
    scope:
      path: ""
      type: "work"
    values:
      layout: "work-item"
      parentTitle: "Works"
      parentUrl: "/works"
  -
    scope:
      path: ""
      type: "coverletter"
    values:
      layout: "coverletter"